In [1]:
import pandas as pd

In [2]:
# Load Data from cohort database (schema week06). See "Data Access (SQL).md".
import sys, pathlib
_p = pathlib.Path.cwd()
while _p != _p.parent and not (_p / "db" / "dataraflow_db.py").exists():
    _p = _p.parent
sys.path.insert(0, str(_p))
from db.dataraflow_db import run_query

data = run_query("SELECT * FROM week06.who_pop_tb_some")
data

                  Country  Population (1000s)  TB deaths
0                  Angola               21472       6900
1                  Brazil              200362       4400
2                   China             1393337      41000
3       Equatorial Guinea                 757         67
4           Guinea-Bissau                1704       1200
5                   India             1252140     240000
6              Mozambique               25834      18000
7                Portugal               10608        140
8      Russian Federation              142834      17000
9   Sao Tome and Principe                 193         18
10           South Africa               52776      25000
11            Timor-Leste                1133        990

### Calculations on a column

In [3]:
tbColumn = data['TB deaths']
tbColumn.sum()

np.int64(354715)

In [4]:
tbColumn.min()

np.int64(18)

In [5]:
tbColumn.max()

np.int64(240000)

In [8]:
tbColumn.sum() / 12

np.float64(29559.583333333332)

In [9]:
tbColumn.mean()

np.float64(29559.583333333332)

Getting the min and max number of deaths

In [12]:
print("country with the minimum number of TB deaths:")
data.sort_values('TB deaths').head(1)

country with the minimum number of TB deaths:

                 Country  Population (1000s)  TB deaths
9  Sao Tome and Principe                 193         18

In [13]:

print("country with the maximum number of TB deaths:")
data.sort_values('TB deaths').tail(1)

country with the maximum number of TB deaths:

  Country  Population (1000s)  TB deaths
5   India             1252140     240000

Sorting by strings

In [19]:
data.sort_values('Country').head(5)

             Country  Population (1000s)  TB deaths
0             Angola               21472       6900
1             Brazil              200362       4400
2              China             1393337      41000
3  Equatorial Guinea                 757         67
4      Guinea-Bissau                1704       1200

Least and most populous countries

In [21]:
print("country with the least population:")
data.sort_values('Population (1000s)').head(1)

country with the least population:

                 Country  Population (1000s)  TB deaths
9  Sao Tome and Principe                 193         18

In [22]:
print("country with the most population:")
data.sort_values('Population (1000s)').tail(1)

country with the most population:

  Country  Population (1000s)  TB deaths
2   China             1393337      41000

### Calculations over columns

Calculating the death rate of each country

In [23]:
deathsColumn = data['TB deaths']
populationColumn = data['Population (1000s)']
rateColumn = deathsColumn * 100 / populationColumn

rateColumn

0     32.134873
1      2.196025
2      2.942576
3      8.850727
4     70.422535
5     19.167186
6     69.675621
7      1.319759
8     11.901928
9      9.326425
10    47.370017
11    87.378641
dtype: float64

In [25]:
data['TB deaths (per 100,000)'] = rateColumn

data.head()

             Country  Population (1000s)  TB deaths  TB deaths (per 100,000)
0             Angola               21472       6900                32.134873
1             Brazil              200362       4400                 2.196025
2              China             1393337      41000                 2.942576
3  Equatorial Guinea                 757         67                 8.850727
4      Guinea-Bissau                1704       1200                70.422535