In [1]:
import pandas as pd

In [3]:
# Load Data from cohort database (schema week06). See "Data Access (SQL).md".
import sys, pathlib
_p = pathlib.Path.cwd()
while _p != _p.parent and not (_p / "db" / "dataraflow_db.py").exists():
    _p = _p.parent
sys.path.insert(0, str(_p))
from db.dataraflow_db import run_query

df = run_query("SELECT * FROM week06.who_pop_tb_all")
df

                                Country  Population (1000s)  TB deaths
0                           Afghanistan               30552   13000.00
1                               Albania                3173      20.00
2                               Algeria               39208    5100.00
3                               Andorra                  79       0.26
4                                Angola               21472    6900.00
..                                  ...                 ...        ...
189  Venezuela (Bolivarian Republic of)               30405     480.00
190                            Viet Nam               91680   17000.00
191                               Yemen               24407     990.00
192                              Zambia               14539    3600.00
193                            Zimbabwe               14150    5700.00

[194 rows x 3 columns]

In [4]:
df.columns

Index(['Country', 'Population (1000s)', 'TB deaths'], dtype='str')

### Dataframe Rows

In [8]:
print("first row, index 0:")
df.iloc[0]

first row, index 0:

Country               Afghanistan
Population (1000s)          30552
TB deaths                 13000.0
Name: 0, dtype: object

In [9]:
print("third row, index 2:")
df.iloc[2]

third row, index 2:

Country               Algeria
Population (1000s)      39208
TB deaths              5100.0
Name: 2, dtype: object

In [10]:
df.head()

       Country  Population (1000s)  TB deaths
0  Afghanistan               30552   13000.00
1      Albania                3173      20.00
2      Algeria               39208    5100.00
3      Andorra                  79       0.26
4       Angola               21472    6900.00

In [11]:
df.tail()

                                Country  Population (1000s)  TB deaths
189  Venezuela (Bolivarian Republic of)               30405      480.0
190                            Viet Nam               91680    17000.0
191                               Yemen               24407      990.0
192                              Zambia               14539     3600.0
193                            Zimbabwe               14150     5700.0

### Getting and displaying dataframe columns

In [13]:
# returns a Series - comes with no column names
df['TB deaths']

0      13000.00
1         20.00
2       5100.00
3          0.26
4       6900.00
         ...
189      480.00
190    17000.00
191      990.00
192     3600.00
193     5700.00
Name: TB deaths, Length: 194, dtype: float64

In [14]:
df['TB deaths'].head()

0    13000.00
1       20.00
2     5100.00
3        0.26
4     6900.00
Name: TB deaths, dtype: float64

In [15]:
df['TB deaths'].tail()

189      480.0
190    17000.0
191      990.0
192     3600.0
193     5700.0
Name: TB deaths, dtype: float64

In [18]:
df['TB deaths'].iloc[2]

np.float64(5100.0)

However, pandas does provide a mechanism for you to get and display one or more selected columns as a new dataframe in its own right. To do this you need to use a list.

A list in Python consists of one or more items separated by commas and enclosed within square brackets, for example ['Country'] or ['Country', 'Population(1000s)']. This list is then put within outer square brackets immediately after the dataframe’s name, like this:

In [19]:
df[['TB deaths']].head()

   TB deaths
0   13000.00
1      20.00
2    5100.00
3       0.26
4    6900.00

In [20]:
df[['Country', 'TB deaths']].head()

       Country  TB deaths
0  Afghanistan   13000.00
1      Albania      20.00
2      Algeria    5100.00
3      Andorra       0.26
4       Angola    6900.00

In [21]:
df[['Country', 'Population (1000s)']].head()

       Country  Population (1000s)
0  Afghanistan               30552
1      Albania                3173
2      Algeria               39208
3      Andorra                  79
4       Angola               21472

#### Comparison Operations

In [22]:
df['Country'] >= 'K'

0      False
1      False
2      False
3      False
4      False
       ...
189     True
190     True
191     True
192     True
193     True
Name: Country, Length: 194, dtype: bool

In [25]:
df[df['Country'] >= 'K'].head()

       Country  Population (1000s)  TB deaths
87  Kazakhstan               16441     1600.0
88       Kenya               44354     9100.0
89    Kiribati                 102       30.0
90      Kuwait                3369       33.0
91  Kyrgyzstan                5548      620.0

In [26]:
df[df['Population (1000s)'] > 80000].head()

       Country  Population (1000s)  TB deaths
13  Bangladesh              156595    80000.0
23      Brazil              200362     4400.0
36       China             1393337    41000.0
53       Egypt               82056      550.0
58    Ethiopia               94101    30000.0

#### Bitwise Operators

In [30]:
(df['Country'] >= 'Nigeria') & (df['Population (1000s)'] > 80000)

0      False
1      False
2      False
3      False
4      False
       ...
189    False
190     True
191    False
192    False
193    False
Length: 194, dtype: bool

In [31]:
df[(df['Country'] >= 'Nigeria') & (df['Population (1000s)'] > 80000)]

                      Country  Population (1000s)  TB deaths
124                   Nigeria              173615   160000.0
128                  Pakistan              182143    49000.0
134               Philippines               98394    27000.0
141        Russian Federation              142834    17000.0
185  United States of America              320051      490.0
190                  Viet Nam               91680    17000.0

In [32]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 194 entries, 0 to 193
Data columns (total 3 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Country             194 non-null    str
 1   Population (1000s)  194 non-null    int64
 2   TB deaths           194 non-null    float64
dtypes: float64(1), int64(1), str(1)
memory usage: 4.7 KB

**If the same columns will be used repeatedly in the program, the code becomes more readable if written as follows**

In [33]:
population = df['Population (1000s)']
deaths = df['TB deaths']

df[(population > 80000) & (deaths > 10000)]

                Country  Population (1000s)  TB deaths
13           Bangladesh              156595    80000.0
36                China             1393337    41000.0
58             Ethiopia               94101    30000.0
77                India             1252140   240000.0
78            Indonesia              249866    64000.0
124             Nigeria              173615   160000.0
128            Pakistan              182143    49000.0
134         Philippines               98394    27000.0
141  Russian Federation              142834    17000.0
190            Viet Nam               91680    17000.0