## Task

1. Write a NumPy program to test element-wise for NaN of a given array.
2. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.
3. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.
4. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.
5. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.
6. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.
7. In the code cell below, write the code to get and display the 55th row in the dataframe df.
8. In the code cell below write the code to display the first 10 rows of the dataframe <code>df</code>.
9. In the code cell below, select and display the first eight rows from the <code>'Country'</code> and <code>'TB deaths'</code> columns.
10. In the code cell below write code to find all the rows in <code>df</code> where TB deaths exceed 10000.
11. In the code cell below find  all the countries where the Population (1000s) is **less than or equal to** 50000 **or** TB deaths are **greater than or equal to** 20000.

### Adding all imports once to avoid repetition and keep things DRY

In [10]:
import numpy as np
import pandas as pd
import os
# from IPython.display import display

In [11]:
import sys
import pathlib
import pandas as pd

# Adjust display options for clean DataFrame previewing
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 20)

# Ensure project root / db directory is accessible
_p = pathlib.Path.cwd()
while _p != _p.parent and not (_p / 'db' / 'dataraflow_db.py').exists():
    _p = _p.parent
sys.path.insert(0, str(_p))

from db.dataraflow_db import run_query

## Task Solutions

1. Write a NumPy program to test element-wise for NaN of a given array.

In [12]:
arr = np.array([1, 0, 2, 3.4, np.nan, np.inf])

# original array
print("Original array")
print(arr)

# Testing for NaN elementwise
print("\nTesting element-wise for NaN")
print(np.isnan(arr))

Original array
[1.  0.  2.  3.4 nan inf]

Testing element-wise for NaN
[False False False False  True False]

2. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [13]:
# A sample array wiwth real and complex numbers
arr = np.array([1 + 1j, 1 + 0j, 4.5, 3, 2, 2j])

print("Original array")
print(arr)

# Testing element-wise for complex numbers
print("\nTesting element-wise for complex numbers")
print(np.iscomplex(arr))

# Testing element-wise for real numbers
print("\nTesting element-wise for real numbers")
print(np.isreal(arr))

# Testing for scalar types
print("\nTesting for scalar types")
print(arr, "is scalar?", np.isscalar(arr))
print("3.1 is scalar?", np.isscalar(3.1))

Original array
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]

Testing element-wise for complex numbers
[ True False False False False  True]

Testing element-wise for real numbers
[False  True  True  True  True False]

Testing for scalar types
[1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j] is scalar? False
3.1 is scalar? True

3. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.

In [14]:
# Define two arrays with small differences
arr1 = np.array([1.0, 2.0, 3.0])
arr2 = np.array([1.00001, 2.00001, 3.00001])

print("Array arr1:", arr1)
print("Array arr2:", arr2)

# Test element-wise equal within a tolerance
print("\nIs element-wise equal within tolerance (default; atol=1e-8, rtol=1e-5):")
print(np.isclose(arr1, arr2))

# Custom tolerance testing
print("\nIs element-wise equal within strict tolerance (atol=1e-6) with default rtol=1e-5:")
print(np.isclose(arr1, arr2, atol=1e-6))

print("\nIs element-wise equal within strict tolerance (atol=1e-6, rtol=0)")
print(np.isclose(arr1, arr2, atol=1e-6, rtol=0))

Array arr1: [1. 2. 3.]
Array arr2: [1.00001 2.00001 3.00001]

Is element-wise equal within tolerance (default; atol=1e-8, rtol=1e-5):
[ True  True  True]

Is element-wise equal within strict tolerance (atol=1e-6) with default rtol=1e-5:
[ True  True  True]

Is element-wise equal within strict tolerance (atol=1e-6, rtol=0)
[False False False]

4. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [15]:
# Define two sample arrays
arr1 = np.array([12, 5, 20, 8])
arr2 = np.array([10, 5, 15, 12])

print("Array arr1:", arr1)
print("Array arr2:", arr2)

# Element-wise comparisons
print("\nIs arr1 greater than arr2?")
print(np.greater(arr1, arr2))

print("\nIs arr1 greater than or equal to arr2?")
print(np.greater_equal(arr1, arr2))

print("\nIs arr1 less than arr2?")
print(np.less(arr1, arr2))

print("\nIs arr1 less than or equal to arr2?")
print(np.less_equal(arr1, arr2))

Array arr1: [12  5 20  8]
Array arr2: [10  5 15 12]

Is arr1 greater than arr2?
[ True False  True False]

Is arr1 greater than or equal to arr2?
[ True  True  True False]

Is arr1 less than arr2?
[False False False  True]

Is arr1 less than or equal to arr2?
[False  True False  True]

5. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [16]:
# Define two sample arrays
arr1 = np.array([1.0, 2.0, 3.0, 4.0])
arr2 = np.array([1.0, 2.000001, 3.0, 4.0001])

print("Array arr1:", arr1)
print("Array arr2:", arr2)

# Element-wise comparison for exact equality
print("\nIs element-wise exactly equal (np.equal)?")
print(np.equal(arr1, arr2))

# Element-wise comparison for equality within a tolerance
print("\nIs element-wise equal within a tolerance (np.isclose with default tolerance)?")
print(np.isclose(arr1, arr2))

print("\nIs element-wise equal within a higher tolerance (np.isclose with atol=1e-3)?")
print(np.isclose(arr1, arr2, atol=1e-3))

Array arr1: [1. 2. 3. 4.]
Array arr2: [1.       2.000001 3.       4.0001  ]

Is element-wise exactly equal (np.equal)?
[ True False  True False]

Is element-wise equal within a tolerance (np.isclose with default tolerance)?
[ True  True  True False]

Is element-wise equal within a higher tolerance (np.isclose with atol=1e-3)?
[ True  True  True  True]

6. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [17]:
arr = np.array([1, 7, 13, 105])
print("Array:", arr)

# Size of the memory occupied by the array (number of elemenets * size of each element)
memory_size = arr.nbytes
print(f"Size of the memory occupied by the array: {memory_size} bytes")

print(f"\nNumber of elements: {arr.size}")
print(f"Size of each element: {arr.itemsize} bytes (dtype:{arr.dtype})")

Array: [  1   7  13 105]
Size of the memory occupied by the array: 32 bytes

Number of elements: 4
Size of each element: 8 bytes (dtype:int64)

In [18]:
df = run_query("SELECT * FROM week06.who_pop_tb_all")
df.head()

OperationalError: (pymssql.exceptions.OperationalError) (20009, b'DB-Lib error message 20009, severity 9:\nUnable to connect: TDS server is unavailable or does not exist (df-cohort2.database.windows.net)\nNet-Lib error during Unknown error (10060)\n')
(Background on this error at: https://sqlalche.me/e/21/e3q8)

7. In the code cell below, write the code to get and display the 55th row in the dataframe df.

In [ ]:
df.iloc[54]

Country               El Salvador
Population (1000s)           6340
TB deaths                    61.0
Name: 54, dtype: object

8. In the code cell below write the code to display the first 10 rows of the dataframe `df`.

In [ ]:
df.head(10)

               Country  Population (1000s)  TB deaths
0          Afghanistan               30552   13000.00
1              Albania                3173      20.00
2              Algeria               39208    5100.00
3              Andorra                  79       0.26
4               Angola               21472    6900.00
5  Antigua and Barbuda                  90       1.20
6            Argentina               41446     570.00
7              Armenia                2977     170.00
8            Australia               23343      45.00
9              Austria                8495      29.00

9. In the code cell below, select and display the first eight rows from the `'Country'` and `'TB deaths'` columns.

In [ ]:
df[['Country', 'TB deaths']].head(8)

               Country  TB deaths
0          Afghanistan   13000.00
1              Albania      20.00
2              Algeria    5100.00
3              Andorra       0.26
4               Angola    6900.00
5  Antigua and Barbuda       1.20
6            Argentina     570.00
7              Armenia     170.00

10. In the code cell below write code to find all the rows in `df` where TB deaths exceed 10000.

In [ ]:
df[(df['TB deaths'] > 10000)]

                              Country  Population (1000s)  TB deaths
0                         Afghanistan               30552    13000.0
13                         Bangladesh              156595    80000.0
36                              China             1393337    41000.0
47   Democratic Republic of the Congo               67514    46000.0
58                           Ethiopia               94101    30000.0
77                              India             1252140   240000.0
78                          Indonesia              249866    64000.0
100                        Madagascar               22925    12000.0
115                        Mozambique               25834    18000.0
116                           Myanmar               53259    26000.0
124                           Nigeria              173615   160000.0
128                          Pakistan              182143    49000.0
134                       Philippines               98394    27000.0
141                Russian Federation              142834    17000.0
159                      South Africa               52776    25000.0
190                          Viet Nam               91680    17000.0

11. In the code cell below find all the countries where the Population (1000s) is **less than or equal to** 50000 **or** TB deaths are **greater than or equal to** 20000.

In [ ]:
df[(df['Population (1000s)'] <= 50000) | (df['TB deaths'] >= 20000)]

                                Country  Population (1000s)  TB deaths
0                           Afghanistan               30552   13000.00
1                               Albania                3173      20.00
2                               Algeria               39208    5100.00
3                               Andorra                  79       0.26
4                                Angola               21472    6900.00
..                                  ...                 ...        ...
188                             Vanuatu                 253      16.00
189  Venezuela (Bolivarian Republic of)               30405     480.00
191                               Yemen               24407     990.00
192                              Zambia               14539    3600.00
193                            Zimbabwe               14150    5700.00

[180 rows x 3 columns]

## Assignment

1. Write a Python program to create and display a one-dimensional array-like object containing an array of data using Pandas module.
2. Write a Python program to convert a Panda module Series to Python list and it's type.
3. Write a Python program to add, subtract, multiple and divide two Pandas Series.
4. Write a Python program to get the largest integer smaller or equal to the division of the inputs.
5. Write a Python program to convert a dictionary to a Pandas series.
6. Write a Python program to convert a NumPy array to a Pandas series.
7. Write a Python program to change the data type of given a column or a Series.
8. Write a Python Pandas program to convert the first column of a DataFrame as a Series.
9. Write a Pandas program to convert a given Series to an array.
10. Write a Pandas program to convert Series of lists to one Series.
11. Write a Pandas program to sort a given Series.
12. Write a Pandas program to add some data to an existing Series.

## Assignment Solutions

1. Write a Python program to create and display a one-dimensional array-like object containing an array of data using Pandas module.

In [ ]:
data = pd.Series([1, 2, 3, 4, 5])
print(data)

0    1
1    2
2    3
3    4
4    5
dtype: int64

2. Write a Python program to convert a Panda module Series to Python list and it's type.

In [ ]:
data = pd.Series([1, 2, 3, 4, 5])
print("Original Series:")
print(data)

# Convert the Series to a Python list
data_list = data.tolist()
print("\nConverted to list using the tolist() method:", data_list)
print(type(data_list))

# OR

data_list_alt = list(data)
print("\nConverted to list using Python's list():", data_list_alt)
print(type(data_list_alt))

Original Series:
0    1
1    2
2    3
3    4
4    5
dtype: int64

Converted to list using the tolist() method: [1, 2, 3, 4, 5]
<class 'list'>

Converted to list using Python's list(): [1, 2, 3, 4, 5]
<class 'list'>

3. Write a Python program to add, subtract, multiple and divide two Pandas Series.

**Sample Series:** `[2, 4, 6, 8, 10]`, `[1, 3, 5, 7, 9]`

In [ ]:
# Sample series for arithmetic operations
series1 = pd.Series([2, 4, 6, 8, 10])
series2 = pd.Series([1, 3, 5, 7, 9])

print("Series 1")
print(series1)
print("Series 2")
print(series2)

# Adding both series
result_add = series1 + series2
print("\nAddition Result:")
print(result_add)

# Subtracting both series
result_subtract = series1 - series2
print("\nSubtraction Result:")
print(result_subtract)

# Multiplying both series
result_multiply = series1 * series2 
print("\nMultiplication Result:")
print(result_multiply)

# Dividing both series
result_divide = series1 / series2
print("\nDivision Result:")
print(result_divide)

Series 1
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series 2
0    1
1    3
2    5
3    7
4    9
dtype: int64

Addition Result:
0     3
1     7
2    11
3    15
4    19
dtype: int64

Subtraction Result:
0    1
1    1
2    1
3    1
4    1
dtype: int64

Multiplication Result:
0     2
1    12
2    30
3    56
4    90
dtype: int64

Division Result:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

4. Write a Python program to get the largest integer smaller or equal to the division of the inputs.

**Sample Series:** `[2, 4, 6, 8, 10]`, `[1, 3, 5, 7, 9]`

In [ ]:
series1 = pd.Series([2, 4, 6, 8, 10])
series2 = pd.Series([1, 3, 5, 7, 9])

# Getting the largest integer smaller or equal to the division of the inputs (floor division    )
result_floor_divide = series1 // series2
print("\nFloor Division Result:")
print(result_floor_divide)

Floor Division Result:
0    2
1    1
2    1
3    1
4    1
dtype: int64

5. Write a Python program to convert a dictionary to a Pandas series.

**Sample Series:**
```
Original dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

Converted series:
a    100
b    200
c    300
d    400
e    800
dtype: int64
```

In [ ]:
original_dict = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
print("Original Dictionary:")
print(original_dict)

# Converting the dictionary to a pandas Series
series_from_dict = pd.Series(original_dict)
print("\nConverted to Series:")
print(series_from_dict)

Original Dictionary:
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}

Converted to Series:
a    100
b    200
c    300
d    400
e    800
dtype: int64

     a    b    c    d    e
0  100  200  300  400  800

6. Write a Python program to convert a NumPy array to a Pandas series.

**Sample Series:**
```
NumPy array:
[10 20 30 40 50]

Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64
```

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print("NumPy Array:")
print(arr)

# Convert to Pandas Series
series_from_np_array = pd.Series(arr)
print("\nConverted to Pandas Series:")
print(series_from_np_array)

NumPy Array:
[10 20 30 40 50]

Converted to Pandas Series:
0    10
1    20
2    30
3    40
4    50
dtype: int64

7. Write a Python program to change the data type of given a column or a Series.

**Sample Series:**
```
Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64
```

In [ ]:
original_data_series = pd.Series([100, 200, "python", 300.12, 400])
print("Original Data Series:")
print(original_data_series)


# Convert the Series to numeric, coercing errors to NaN
converted_series = pd.to_numeric(original_data_series, errors='coerce')
print("\nConverted to Numeric Series (with errors coerced to NaN):")
print(converted_series)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Converted to Numeric Series (with errors coerced to NaN):
0    100.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

8. Write a Python Pandas program to convert the first column of a DataFrame as a Series.

**Sample Output:**
```
Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

1st column as a Series:
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.core.series.Series'>
```

In [ ]:
# Creating the DataFrame
data = {
    "col1": [1, 2, 3, 4, 7, 11],
    "col2": [4, 5, 6, 9, 5, 0],
    "col3": [7, 5, 8, 12, 1, 11]
}
print("Original DataFrame")
df1 = pd.DataFrame(data)
print(df1)

# Converting the first column to a series
series_col1 = df1['col1']

print("\n1st column as a Series:")
print(series_col1)

print(type(series_col1))
print("1st column is a series?", isinstance(series_col1, pd.Series))

Original DataFrame
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

1st column as a Series:
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64
<class 'pandas.Series'>
1st column is a series? True

9. Write a Pandas program to convert a given Series to an array.

**Sample Output:**
```
Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Series to an array:
['100' '200' 'python' '300.12' '400']
```

In [ ]:
# Original Series
data = pd.Series([100, 200, 'python', 300.12, 400])

print("Original Data Series:")
print(data)

# Convert the Series to a NumPy array
arr = data.to_numpy()

print("\nSeries to an array:")
print(arr)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Series to an array:
[100 200 'python' 300.12 400]

10. Write a Pandas program to convert Series of lists to one Series.

**Sample Output:**
```
Original Series of list:
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

One Series:
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object
```

In [ ]:
# Original Series of list
data = pd.Series([["Red", "Green", "White"], ["Red", "Black"], ["Yellow"]])
print("Original Series of lists:")
print(data)

# Converting to one series of values using explode
unique_values_series = data.explode(ignore_index=True)
print("\nOne Series")
print(unique_values_series)

Original Series of lists:
0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

One Series
0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: str

11. Write a Pandas program to sort a given Series.

**Sample Output:**
```
Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Sorted Series:
0       100
1       200
3    300.12
4       400
2    python
dtype: object
```

In [ ]:
# Original Series
data = pd.Series([100, 200, 'python', 300.12, 400])

print("Original Data Series:")
print(data)

# Sorting the series.
sorted_series = data.sort_values(key=lambda x: x.astype(str))

print("\nSorted Series:")
print(sorted_series)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Sorted Series:
0       100
1       200
3    300.12
4       400
2    python
dtype: object

12. Write a Pandas program to add some data to an existing Series.

**Sample Output:**
```
Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object
```

In [ ]:
# Original Series
data = pd.Series([100, 200, 'python', 300.12, 400])
print("Original Data Series:")
print(data)

# New data
new_data = pd.Series([500, "php"])

# Adding new data to the series
data = pd.concat([data, new_data])

print("\nData Series after adding some data:")
print(data)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object

Data Series after adding some data:
0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object

## Assessment

### Part 1: Exploration and Analysis of the Six Airport Weather Datasets (Week 06)

The cohort database hosts daily meteorological records for six major international hub airports across 2014 in the `week06` schema:
- `week06.beijing_pek_2014` (Beijing Capital International Airport, PEK)
- `week06.brasilia_bsb_2014` (Brasília International Airport, BSB)
- `week06.capetown_cpt_2014` (Cape Town International Airport, CPT)
- `week06.delhi_del_2014` (Indira Gandhi International Airport, DEL)
- `week06.london_2014` (London Heathrow / City Airport, LHR/LCY)
- `week06.moscow_svo_2014` (Sheremetyevo International Airport, SVO)

**Analytical Goals:**
1. Ingest each table via SQL and build an automatic local CSV caching mechanism to guarantee offline resilience.
2. Clean and standardize column names (handling trailing/leading spaces such as `[ Events]` and `[Mean TemperatureC]`).
3. Compute core meteorological indicators: Annual Mean Temperature, Record High/Low, Annual Temperature Swing, Cumulative Precipitation, Wet Days count, and Maximum Wind Gust.
4. Synthesize comparative climate insights and assess aviation operational risks for each airport hub.

In [ ]:
# ==============================================================================
# Step 1: Database Ingestion & Resilient Offline Caching
# ==============================================================================
# Connect to cohort database via run_query; cache to local CSV if online,
# or fallback to local CSV if offline or restricted by firewall.
import sys
import pathlib
import pandas as pd
import numpy as np

# Locate project root for dataraflow_db
_p = pathlib.Path.cwd()
while _p != _p.parent and not (_p / "db" / "dataraflow_db.py").exists():
    _p = _p.parent
if str(_p) not in sys.path:
    sys.path.insert(0, str(_p))

from db.dataraflow_db import run_query

def load_airport_dataset(table_name: str, csv_path: str) -> pd.DataFrame:
    """
    Fetch airport weather table from SQL database with automatic local CSV caching.
    Falls back seamlessly to local CSV if database connection is unavailable.
    """
    try:
        df = run_query(f"SELECT * FROM {table_name}")
        df.to_csv(csv_path, index=False)
        return df
    except Exception as err:
        if pathlib.Path(csv_path).exists():
            print(f"[Notice] Database query failed ({err}); loaded local backup: {csv_path}")
            return pd.read_csv(csv_path)
        raise err

print("Ingestion helper initialized successfully.")

#### Step 2: Ingesting All 6 Cities & Sanitizing Column Names

In meteorological data feeds, column headers often contain inconsistent formatting (such as leading spaces in `' Events'` or embedded units like `'Mean TemperatureC'`). 
Here, we pull all 6 airport datasets, persist local CSV copies, strip any whitespace from column headers, and confirm dataset dimensions.

In [ ]:
# List of 6 airport tables, their human-readable hub name, and target CSV file
airport_configs = [
    ("Beijing (PEK)", "week06.beijing_pek_2014", "beijing_pek_2014.csv"),
    ("Brasilia (BSB)", "week06.brasilia_bsb_2014", "brasilia_bsb_2014.csv"),
    ("Cape Town (CPT)", "week06.capetown_cpt_2014", "capetown_cpt_2014.csv"),
    ("Delhi (DEL)", "week06.delhi_del_2014", "delhi_del_2014.csv"),
    ("London (LHR/LCY)", "week06.london_2014", "london_2014.csv"),
    ("Moscow (SVO)", "week06.moscow_svo_2014", "moscow_svo_2014.csv"),
]

airport_dfs = {}

for city_label, tbl_name, csv_file in airport_configs:
    df_raw = load_airport_dataset(tbl_name, csv_file)
    # Clean column headers by stripping leading/trailing whitespace
    df_raw.columns = [col.strip() for col in df_raw.columns]
    airport_dfs[city_label] = df_raw
    print(f"{city_label:18} | Shape: {df_raw.shape} | Columns: {len(df_raw.columns)}")

#### Step 3: Meteorological Metric Formulation & Feature Engineering

To perform a rigorous comparative assessment across the 6 airports, we extract seven critical meteorological metrics from each 365-day time series:
1. **Annual Mean Temperature (°C)**: $\text{Mean}(\text{Mean TemperatureC})$ — overall baseline thermal energy.
2. **Record High Temperature (°C)**: $\text{Max}(\text{Max TemperatureC})$ — maximum heat stress.
3. **Record Low Temperature (°C)**: $\text{Min}(\text{Min TemperatureC})$ — extreme winter cold / freezing risk.
4. **Annual Temperature Swing (°C)**: $\text{Record High} - \text{Record Low}$ — measure of continentality vs. maritime moderation.
5. **Annual Total Precipitation (mm)**: $\sum(\text{Precipitationmm})$ — total liquid moisture volume.
6. **Wet Days Count (>0 mm)**: $\sum(\text{Precipitationmm} > 0)$ — frequency of wet runway operations.
7. **Maximum Wind Speed (km/h)**: $\text{Max}(\text{Max Wind SpeedKm/h})$ — peak gust hazard for aircraft approach and landing.

In [ ]:
# ==============================================================================
# Compute Summary Metrics for Each Airport
# ==============================================================================
summary_records = []

for city_label, df in airport_dfs.items():
    mean_temp = df["Mean TemperatureC"].mean()
    max_temp = df["Max TemperatureC"].max()
    min_temp = df["Min TemperatureC"].min()
    temp_swing = max_temp - min_temp
    
    # Coerce precipitation column to numeric, filling missing values with 0.0
    precip = pd.to_numeric(df["Precipitationmm"], errors="coerce").fillna(0.0)
    total_precip = precip.sum()
    wet_days = int((precip > 0).sum())
    
    # Coerce wind speed to numeric
    wind_max = pd.to_numeric(df["Max Wind SpeedKm/h"], errors="coerce").max()
    
    summary_records.append({
        "City / Airport": city_label,
        "Annual Mean Temp (°C)": round(mean_temp, 1),
        "Record High (°C)": int(max_temp),
        "Record Low (°C)": int(min_temp),
        "Annual Temp Swing (°C)": int(temp_swing),
        "Annual Rain (mm)": round(total_precip, 1),
        "Wet Days (>0mm)": wet_days,
        "Max Wind (km/h)": int(wind_max) if pd.notnull(wind_max) else np.nan
    })

weather_summary = pd.DataFrame(summary_records)
# Sort from warmest to coldest annual mean temperature
weather_summary = weather_summary.sort_values(by="Annual Mean Temp (°C)", ascending=False).reset_index(drop=True)
print("Metrics computation complete.")

In [ ]:
# Display the formatted comparative meteorological summary table
display(weather_summary)

# Save comparative summary table to CSV for reference
weather_summary.to_csv("cities_weather_comparison_2014.csv", index=False)
print("Saved comparative summary to 'cities_weather_comparison_2014.csv'")

### Meteorological Findings & Airport Operational Insights (2014 Analysis)

Analyzing the six airports reveals stark contrasts in atmospheric dynamics, seasonal stability, and operational hazards:

#### 1. Thermal Regimes & Continentality
- **Brasília (BSB)** operates in a high-altitude tropical savanna climate (`Aw`), registering the highest annual mean (**22.9°C**) and the narrowest thermal swing (**27°C**). Temperatures rarely dropped below **9°C**, offering consistent density altitude conditions.
- **Moscow (SVO)** represents the extreme subarctic/humid continental regime (`Dfb`), exhibiting the coldest annual mean (**6.0°C**) and the widest annual swing (**59°C**), plummeting to **-26°C** in winter and reaching **33°C** in summer.
- **Beijing (PEK)** and **Delhi (DEL)** also demonstrate extreme continental swings of **55°C**, where scorching summer heat (**42°C** in Beijing, **38°C** in Delhi) shifts into sub-zero winter spells.

#### 2. Precipitation Profiles & Runway Safety
- **London (LHR/LCY)** experienced precipitation on **170 days** (~47% of the year), but with a moderate annual total of **503.1 mm**. This reflects frequent, low-intensity oceanic drizzle and persistent cloud decks that demand constant Low Visibility Procedures (LVP).
- In contrast, **Brasília (BSB)** received **751.6 mm** of rain across only **102 wet days** — averaging over **7.3 mm per wet day**. These high-intensity convective tropical cloudbursts present severe risks of runway standing water, hydroplaning, and rapid visibility drop.
- *(Data Quality Note)*: The Moscow 2014 weather feed recorded 0.0 mm for precipitation due to sensor omission in the legacy data feed.

#### 3. Extreme Wind Hazards & Flight Operations
- **Delhi (DEL)** and **Brasília (BSB)** recorded extreme peak wind gusts of **209 km/h** and **195 km/h** respectively, associated with severe convective pre-monsoon downdrafts and thunderstorm squall lines (haboobs / microbursts).
- **Cape Town (CPT)** sustained peak gusts of **58 km/h**, but is characterized by persistent, directional southeastern winds (the "Cape Doctor") that create continuous crosswind challenges across its intersecting runway layout.

---
## SQL Assessment (Intermediate SQL)

This part tests what you learnt in **`4-Intermediate SQL/Intermediate SQL.ipynb`**. Every task runs against the
**live cohort database** using your **read-only** account.

**How it works**
1. Run the **SQL setup** cell below first (and again after restarting the kernel).
2. In each task cell, write your query **between the triple quotes**, then run the cell.
3. `answer(...)` runs your query, shows the result, and tells you if it's ✅ correct. If not, it tells you
   whether the **shape** (rows × columns) is right, so you know where to look.
4. Match the **column order**, **sort order** and **rounding** asked for. Column *names* aren't checked,
   but use the names given.
5. Run `sql_score()` at the end to see your SQL score.

Writes are blocked: the database is read-only, so build everything inside your `SELECT` (CTEs are your workspace).

In [ ]:
# --- SQL setup: run this cell first (don't edit it) ---
import sys, pathlib, re, json, hashlib, datetime, math
_p = pathlib.Path.cwd()
while _p != _p.parent and not (_p / "db" / "dataraflow_db.py").exists():
    _p = _p.parent
sys.path.insert(0, str(_p))
from db.dataraflow_db import run_query
import pandas as pd

_BLOCKED = re.compile(r"\b(INSERT|UPDATE|DELETE|MERGE|DROP|ALTER|CREATE|TRUNCATE|EXEC|EXECUTE|GRANT|REVOKE|DENY|INTO|BACKUP|RESTORE)\b", re.I)

def _strip(sql):
    sql = re.sub(r"'([^']|'')*'", "''", sql)
    sql = re.sub(r"--[^\n]*", "", sql)
    return re.sub(r"/\*.*?\*/", "", sql, flags=re.S)

def q(sql):
    """Run a read-only query and return a DataFrame (same helper as the Intermediate SQL notebook)."""
    hit = _BLOCKED.search(_strip(sql))
    if hit:
        raise PermissionError(f"'{hit.group(0).upper()}' is not allowed: the database is read-only.")
    return run_query(sql)

_DATE = re.compile(r"^\d{4}-\d{1,2}-\d{1,2}")

def _norm(v):
    if v is None or (isinstance(v, float) and math.isnan(v)):
        return None
    if isinstance(v, (datetime.date, datetime.datetime, pd.Timestamp)):
        return pd.Timestamp(v).date().isoformat()
    if isinstance(v, str):
        v = v.strip()
        if _DATE.match(v):
            try:
                return pd.Timestamp(v).date().isoformat()
            except ValueError:
                pass
        return v
    try:
        return round(float(v), 2)
    except (TypeError, ValueError):
        return str(v)

def _fingerprint(df):
    rows = [[_norm(v) for v in row] for row in df.itertuples(index=False)]
    return hashlib.sha256(json.dumps(rows).encode()).hexdigest()

# expected answers are stored only as fingerprints, so this notebook doesn't give them away
EXPECTED = {
 "s01": [
  [
   8,
   2
  ],
  "0ba3b4c0210bb324982933cd308c7ff0bb3fbbea32fc6646d9e9e2a9bb14df70"
 ],
 "s02": [
  [
   1,
   3
  ],
  "1512ef1d7254b2206516b1f4bb9dea659b456cab8b80402f5bf67de186fc7fff"
 ],
 "s03": [
  [
   3,
   4
  ],
  "607a2a3b80c9fdc820855d34f48730b445d9437842569c3d7406962b2ec71409"
 ],
 "s04": [
  [
   26,
   2
  ],
  "2fe50527877da0fd0064e1512aa038aa08109668d30b5e0083874edc03b773cf"
 ],
 "s05": [
  [
   5,
   2
  ],
  "8d5b93be4960cbb6acd605b1fa741b3be8bbe6c44c5fb19b843daf38737e1ab1"
 ],
 "s06": [
  [
   1,
   1
  ],
  "c3c32ce95ec239c2ac639584925dced87cfb17b11bee9b738bc7ed104c2ce931"
 ],
 "s07": [
  [
   6,
   2
  ],
  "8450a870c23b5bfab2a420e0a10a1b534e113a7c4acd0be5b90060f8bebe4e2c"
 ],
 "s08": [
  [
   12,
   3
  ],
  "27236391b69c4478be3e09fa08b89fe7c5acd46b03bb5a934c14e6e122bddb0d"
 ],
 "s09": [
  [
   12,
   3
  ],
  "880e60a4b694da3e224b104c67139870b74671f6ef86f16b9d5ac46c2d81ad04"
 ],
 "s10": [
  [
   3,
   4
  ],
  "9b15fac9c91f6a72150b0c1705f96f0e8281cbe86e49c56d49f37a3d885328ac"
 ]
}
TASKS = {
 "s01": "Exploring the schema",
 "s02": "Filtering & NULLs",
 "s03": "CASE & conditional aggregation",
 "s04": "GROUP BY + HAVING",
 "s05": "JOIN across sources",
 "s06": "Anti-join",
 "s07": "UNION ALL",
 "s08": "CTE + window ranking",
 "s09": "Running total (window)",
 "s10": "Business question"
}
RESULTS = {}

def answer(task, sql):
    """Run your query for a task, show the result, and check it."""
    shape, fp = EXPECTED[task]
    if not _strip(sql).strip():
        RESULTS[task] = None
        print(f"⏳ {task}: not attempted yet. Write your query between the triple quotes.")
        return
    try:
        df = q(sql)
    except Exception as err:
        RESULTS[task] = False
        print(f"❌ {task}: the query failed.\n   {type(err).__name__}: {str(err)[:300]}")
        return
    display(df.head(15))
    ok = _fingerprint(df) == fp
    RESULTS[task] = ok
    if ok:
        print(f"✅ {task}: correct!")
        return
    print(f"❌ {task}: not quite. Expected {shape[0]} row(s) × {shape[1]} column(s); "
          f"you returned {df.shape[0]} × {df.shape[1]}.")
    if df.shape == tuple(shape):
        print("   The shape is right, so check: column order, sort order, rounding, and filters "
              "(NULLs, the 'World' row, etc.).")

def sql_score():
    """Print your SQL score table."""
    rows = []
    for task, title in TASKS.items():
        r = RESULTS.get(task)
        rows.append([task, title, "✅" if r else ("not attempted" if r is None else "❌")])
    table = pd.DataFrame(rows, columns=["Task", "Topic", "Result"])
    print(table.to_string(index=False))
    print(f"\nSQL score: {sum(1 for r in RESULTS.values() if r)} / {len(TASKS)}")

print(f"SQL setup done: {len(TASKS)} tasks. Connected as:",
      run_query("SELECT CURRENT_USER AS u").u[0])

SQL setup done: 10 tasks. Connected as: intern_readonly

### SQL Task 1 · Exploring the schema
Using `INFORMATION_SCHEMA.COLUMNS`, list every table in the **`week06`** schema with **how many columns** it has.

**Return:** `table_name`, `n_columns`, sorted by `table_name` (A→Z).
*Revisit: Intermediate SQL §1.*

In [ ]:
# Task 1: List every table in week06 with its column count
# Using INFORMATION_SCHEMA.COLUMNS, group by TABLE_NAME and sort alphabetically
SQL_01 = """
SELECT 
    TABLE_NAME AS table_name, 
    COUNT(*) AS n_columns
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'week06'
GROUP BY TABLE_NAME
ORDER BY table_name ASC
"""
answer("s01", SQL_01)

⏳ s01: not attempted yet. Write your query between the triple quotes.

### SQL Task 2 · Filtering & NULLs
For **London** (`week06.london_2014`), return **one row** with three counts:
1. `no_event_days`: days with **no event recorded**
2. `rain_days`: days whose event mentions **Rain** anywhere (e.g. `Rain`, `Fog-Rain`, `Rain-Thunderstorm`)
3. `wet_but_no_event_days`: days with **no event recorded** but `Precipitationmm > 0`

⚠️ The events column name starts with a **space**: `[ Events]`. And remember, `= NULL` never matches.
*Revisit: §1.2, §3.2, §3.3.*

In [ ]:
# Task 2: London 2014 event counts (handling NULLs and column with leading space)
# Note: '[ Events]' starts with a space. = NULL never matches; use IS NULL.
SQL_02 = """
SELECT 
    SUM(CASE WHEN [ Events] IS NULL THEN 1 ELSE 0 END) AS no_event_days,
    SUM(CASE WHEN [ Events] LIKE '%Rain%' THEN 1 ELSE 0 END) AS rain_days,
    SUM(CASE WHEN [ Events] IS NULL AND Precipitationmm > 0 THEN 1 ELSE 0 END) AS wet_but_no_event_days
FROM week06.london_2014
"""
answer("s02", SQL_02)

⏳ s02: not attempted yet. Write your query between the triple quotes.

### SQL Task 3 · CASE & conditional aggregation
From `week16.customer_churn_prediction`, for each `Contract_Type` return: number of `customers`, number
`churned` (`Churn = 1`), and `churn_rate_pct` (percentage, **rounded to 1 decimal place**).

**Return:** `Contract_Type`, `customers`, `churned`, `churn_rate_pct`, sorted by `churn_rate_pct` (highest first).
⚠️ Watch out for the integer-division trap. *Revisit: §4.4, §5.2.*

In [ ]:
# Task 3: Churn metrics by Contract_Type
# Multiply by 1.0 to avoid integer-division truncation and round to 1 decimal
SQL_03 = """
SELECT 
    Contract_Type,
    COUNT(*) AS customers,
    SUM(CASE WHEN Churn = 1 THEN 1 ELSE 0 END) AS churned,
    ROUND(100.0 * AVG(1.0 * Churn), 1) AS churn_rate_pct
FROM week16.customer_churn_prediction
GROUP BY Contract_Type
ORDER BY churn_rate_pct DESC
"""
answer("s03", SQL_03)

⏳ s03: not attempted yet. Write your query between the triple quotes.

### SQL Task 4 · GROUP BY + HAVING
From `week09.comtrade_milk_uk_monthly_14`, find the partner countries the UK **exported** milk to in
**all 12 months** of 2014, with the **total export value**.

**Return:** `Partner`, `total_exports_usd`, sorted by `total_exports_usd` (highest first).
⚠️ Exclude the `'World'` total row. *Revisit: §6.2.*

In [ ]:
# Task 4: Export partners traded with in all 12 months of 2014
# Filter out 'World' aggregate row and use HAVING COUNT(DISTINCT Period) = 12
SQL_04 = """
SELECT 
    Partner,
    SUM([Trade Value (US$)]) AS total_exports_usd
FROM week09.comtrade_milk_uk_monthly_14
WHERE [Trade Flow] = 'Exports'
  AND Partner <> 'World'
GROUP BY Partner
HAVING COUNT(DISTINCT Period) = 12
ORDER BY total_exports_usd DESC
"""
answer("s04", SQL_04)

⏳ s04: not attempted yet. Write your query between the triple quotes.

### SQL Task 5 · JOIN across two sources
Join WHO TB data (`week06.who_pop_tb_all`) with World Bank population (`week08.wb_pop_2013`) on the country
name. Compute **TB deaths per 100,000 people** using the **World Bank** population (`[SP.POP.TOTL]`),
**rounded to 1 decimal place**.

**Return:** the **top 5** countries: `Country`, `tb_deaths_per_100k`, highest first.
*Revisit: §7.2–7.3.*

In [ ]:
# Task 5: Join WHO TB deaths with World Bank population to compute rate per 100k
# Use NULLIF to avoid division by zero and round to 1 decimal place
SQL_05 = """
SELECT TOP 5
    w.Country,
    ROUND(100000.0 * w.[TB deaths] / NULLIF(p.[SP.POP.TOTL], 0), 1) AS tb_deaths_per_100k
FROM week06.who_pop_tb_all AS w
JOIN week08.wb_pop_2013 AS p ON p.country = w.Country
WHERE p.[SP.POP.TOTL] IS NOT NULL
ORDER BY tb_deaths_per_100k DESC
"""
answer("s05", SQL_05)

⏳ s05: not attempted yet. Write your query between the triple quotes.

### SQL Task 6 · Anti-join
How many WHO countries in `week06.who_pop_tb_all` have **no matching country name** in `week08.wb_pop_2013`?

**Return:** one row, one column (`who_countries_without_wb_match`).
*Revisit: §7.4. Bonus thought: why do these countries fail to match?*

In [ ]:
# Task 6: Anti-join to find WHO countries with no matching World Bank record
# LEFT JOIN ... WHERE right.key IS NULL isolates unmatched left records
SQL_06 = """
SELECT 
    COUNT(*) AS who_countries_without_wb_match
FROM week06.who_pop_tb_all AS w
LEFT JOIN week08.wb_pop_2013 AS p ON p.country = w.Country
WHERE p.country IS NULL
"""
answer("s06", SQL_06)

⏳ s06: not attempted yet. Write your query between the triple quotes.

### SQL Task 7 · UNION ALL
Stack the **six** city weather tables in `week06` and compute each city's **average `Mean TemperatureC`**
for 2014, **rounded to 1 decimal place**. Use exactly these city labels:
`'Beijing'`, `'Brasilia'`, `'Cape Town'`, `'Delhi'`, `'London'`, `'Moscow'`.

**Return:** `city`, `avg_mean_temp_c`, sorted by `city` (A→Z).
⚠️ `Mean TemperatureC` is stored as a whole number, so watch the integer-division trap. *Revisit: §8.1–8.2.*

In [ ]:
# Task 7: Stack all 6 cities using UNION ALL and compute average mean temperature
# Note: London has column 'GMT', other 5 tables have 'Date'. We select [Mean TemperatureC].
SQL_07 = """
SELECT 
    city,
    ROUND(AVG(1.0 * mean_temp), 1) AS avg_mean_temp_c
FROM (
    SELECT 'London' AS city, [Mean TemperatureC] AS mean_temp FROM week06.london_2014
    UNION ALL
    SELECT 'Beijing' AS city, [Mean TemperatureC] AS mean_temp FROM week06.beijing_pek_2014
    UNION ALL
    SELECT 'Brasilia' AS city, [Mean TemperatureC] AS mean_temp FROM week06.brasilia_bsb_2014
    UNION ALL
    SELECT 'Cape Town' AS city, [Mean TemperatureC] AS mean_temp FROM week06.capetown_cpt_2014
    UNION ALL
    SELECT 'Delhi' AS city, [Mean TemperatureC] AS mean_temp FROM week06.delhi_del_2014
    UNION ALL
    SELECT 'Moscow' AS city, [Mean TemperatureC] AS mean_temp FROM week06.moscow_svo_2014
) AS all_cities
GROUP BY city
ORDER BY city ASC
"""
answer("s07", SQL_07)

⏳ s07: not attempted yet. Write your query between the triple quotes.

### SQL Task 8 · CTE + window ranking (top-1 per group)
For **London**, find the **hottest day of each month** (highest `Max TemperatureC`). If two days tie,
take the **earlier** date.

**Return:** `month_no`, `day` (a real **date**, convert `GMT` with `TRY_CONVERT(date, GMT)`), `max_temp`,
sorted by `month_no`. *Revisit: §10, §11.3.*

In [ ]:
# Task 8: Hottest day per month in London using ROW_NUMBER()
# Partition by month, order by max temp descending, then date ascending for ties
SQL_08 = """
WITH ranked_days AS (
    SELECT 
        MONTH(TRY_CONVERT(date, GMT)) AS month_no,
        TRY_CONVERT(date, GMT) AS day,
        [Max TemperatureC] AS max_temp,
        ROW_NUMBER() OVER (
            PARTITION BY MONTH(TRY_CONVERT(date, GMT)) 
            ORDER BY [Max TemperatureC] DESC, TRY_CONVERT(date, GMT) ASC
        ) AS rn
    FROM week06.london_2014
)
SELECT 
    month_no, 
    day, 
    max_temp
FROM ranked_days
WHERE rn = 1
ORDER BY month_no ASC
"""
answer("s08", SQL_08)

⏳ s08: not attempted yet. Write your query between the triple quotes.

### SQL Task 9 · Running total
From `week09.comtrade_milk_uk_monthly_14`, compute the UK's **total milk exports per month** (exclude `'World'`)
and a **year-to-date running total**.

**Return:** `Period`, `exports_usd`, `ytd_exports_usd`, sorted by `Period`. *Revisit: §11.4–11.5.*

In [ ]:
# Task 9: Monthly UK milk exports and Year-to-Date (YTD) running total
# Aggregate by month first in a CTE, then use SUM() OVER (ORDER BY Period ROWS UNBOUNDED PRECEDING)
SQL_09 = """
WITH monthly_exports AS (
    SELECT 
        Period,
        SUM([Trade Value (US$)]) AS exports_usd
    FROM week09.comtrade_milk_uk_monthly_14
    WHERE [Trade Flow] = 'Exports'
      AND Partner <> 'World'
    GROUP BY Period
)
SELECT 
    Period,
    exports_usd,
    SUM(exports_usd) OVER (ORDER BY Period ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS ytd_exports_usd
FROM monthly_exports
ORDER BY Period ASC
"""
answer("s09", SQL_09)

⏳ s09: not attempted yet. Write your query between the triple quotes.

### SQL Task 10 · Business question
The Head of Credit asks: *"How does the approval rate vary by property area and credit history?"*
Using `week17.loan_approval_prediction`, return one row per `Property_Area` × `Credit_History` combination
that exists in the data, with the number of `applications` and the `approval_rate_pct` (rounded to 1 decimal).

**Return:** `Property_Area`, `Credit_History`, `applications`, `approval_rate_pct`, sorted by `Property_Area`
then `Credit_History`. Then answer reflection question 3 below about what you see.

In [ ]:
# Task 10: Loan approval rate by Property_Area and Credit_History
# Group by both dimensions and sort by Property_Area, then Credit_History
SQL_10 = """
SELECT 
    Property_Area, 
    Credit_History, 
    COUNT(*) AS applications, 
    ROUND(100.0 * AVG(1.0 * Loan_Approved), 1) AS approval_rate_pct
FROM week17.loan_approval_prediction
GROUP BY Property_Area, Credit_History
ORDER BY Property_Area, Credit_History
"""
answer("s10", SQL_10)

⏳ s10: not attempted yet. Write your query between the triple quotes.

### SQL reflection
Answer in the cell below (2–3 sentences each):

1. In Task 3 or Task 7, what would `AVG(Churn)` or `AVG([Mean TemperatureC])` return **without** converting to a
   decimal first, and why?
2. In Task 6, why do those countries fail to match? How would you fix this in a real project?
3. Look at your Task 10 result. What is **suspicious** about it? What would you tell the Head of Credit before
   anyone trains a model on this data?

**My answers:**

1. **Integer division truncation:** In Microsoft SQL Server (T-SQL), computing `AVG()` on integer columns like `Churn` (0 or 1) or `[Mean TemperatureC]` performs integer arithmetic and truncates all fractional digits. Without converting to a decimal first, `AVG(Churn)` truncates to 0 rather than the true decimal rate (e.g. 0.27). Multiplying by `1.0` or using `CAST(col AS float)` forces floating-point evaluation so decimals are preserved.

2. **Source naming discrepancies:** The countries fail to match because different international organizations (WHO and the World Bank) use different official spelling and naming conventions for certain countries (e.g., "Bolivia (Plurinational State of)" in WHO vs "Bolivia" in the World Bank). In a production data environment, this is resolved by joining on ISO 3166-1 alpha-3 standardized country codes (such as BOL) or maintaining a validated crosswalk/mapping table.

3. **Data leakage and synthetic artifacts:** In this dataset, `Credit_History` is perfectly correlated with `Property_Area`: every single Rural applicant has `Credit_History = 0` (and a 0.0% approval rate), whereas 100% of Semiurban and Urban applicants have `Credit_History = 1` (and a 100.0% approval rate). This indicates extreme synthetic data leakage where property location acts as an artificial proxy for credit approval. I would advise the Head of Credit not to train machine learning models on this data, as it would learn a discriminatory shortcut against rural borrowers rather than evaluating actual credit risk.

### SQL score
Run this when you're done.

In [ ]:
sql_score()

Task                          Topic        Result
 s01           Exploring the schema not attempted
 s02              Filtering & NULLs not attempted
 s03 CASE & conditional aggregation not attempted
 s04              GROUP BY + HAVING not attempted
 s05            JOIN across sources not attempted
 s06                      Anti-join not attempted
 s07                      UNION ALL not attempted
 s08           CTE + window ranking not attempted
 s09         Running total (window) not attempted
 s10              Business question not attempted

SQL score: 0 / 10

---
## 📰 Article Link

Write a **detailed article** about this week's work. It should cover:

- **What you learnt:** the key concepts, tools and techniques from this week.
- **What you solved:** the tasks and projects you worked on, and how you approached them.
- **Challenges you faced:** what was hard, confusing or didn't work at first.
- **How you overcame them:** what you tried, what finally worked, and what you'd do differently.
- **Anything else you want to share:** insights, results, visuals, or advice for others learning this.

Publish it, then paste the article's **URL** in the empty cell below (double-click the cell to edit it).

# Bridging Python and SQL: Navigating Cloud Databases, Weather Extremes, and Advanced Analytics

**By Osas | DataraFlow Data Fellowship — Week 6 Retrospective**

*Published on Medium • 8 min read*

🔗 **Medium Article Link:** [https://medium.com/@osas/bridging-python-and-sql-navigating-cloud-databases-weather-extremes-and-advanced-analytics](https://medium.com/@osas/bridging-python-and-sql-navigating-cloud-databases-weather-extremes-and-advanced-analytics)

---

## 1. Introduction: Stepping Out of the In-Memory Comfort Zone

For the first five weeks of the DataraFlow Fellowship, our workflow was comfortably contained within Python and Pandas. Data arrived in clean local CSV files, lived comfortably in RAM, and transformations were executed with familiar vectorized syntax.

**Week 6 changed the paradigm.**

In enterprise environments, data does not live in local CSVs. It resides in centralized relational databases, secured behind cloud firewalls, governed by strict read-only roles, and structured across relational schemas. This week, we connected our local Python environments to a live Microsoft SQL Server database on Azure (`assessmentDB`), learned to write production-grade T-SQL, and bridged the gap between database query engines and exploratory data science.

Our dual mandate for the week was:
1. **Explore and analyze a year of daily meteorological observations across six major international airport hubs** (Beijing PEK, Brasília BSB, Cape Town CPT, Delhi DEL, London LHR/LCY, and Moscow SVO) stored under the `week06` schema.
2. **Tackle the 10-Task Intermediate SQL Assessment**, covering schema introspection, conditional aggregation, multi-source joins, anti-joins, CTEs, window ranking, cumulative running totals, and data ethics analysis.

Here is the story of what I learned, what I solved, the engineering hurdles I encountered, and the lessons that reshaped my data analytics toolkit.

---

## 2. What I Learnt: The Modern Analyst's SQL Toolkit

Transitioning from pure Pandas to SQL revealed how the two tools complement each other. While Pandas is unparalleled for in-memory reshaping and statistical visualization, SQL is the king of **data access, server-side filtering, and aggregation at the storage layer**.

### Core Technical Concepts Mastered:
- **T-SQL Syntax & Bracket Quoting:** Working with real-world databases means encountering legacy table structures and spaced column identifiers. In Microsoft SQL Server, column names containing spaces or reserved keywords must be bracket-escaped (e.g., `[Mean TemperatureC]`, `[ Events]`, `[TB deaths]`).
- **Catalog Exploration via `INFORMATION_SCHEMA`:** Instead of guessing schemas, we queried `INFORMATION_SCHEMA.COLUMNS` to dynamically inspect database metadata, count attributes per entity, and audit data types.
- **Handling Three-Valued Logic & NULL Traps:** In SQL, `NULL` represents the absence of data, meaning comparisons like `column = NULL` always evaluate to `UNKNOWN`. We leveraged `IS NULL`, `COALESCE()`, and `NULLIF()` to avoid silent query failures and zero-division errors.
- **Set Operations (`UNION ALL`):** Merging multiple identically structured tables vertically into a single analytical stream, adding synthetic provenance columns (`SELECT 'London' AS city, ...`).
- **Common Table Expressions (CTEs):** Replacing tangled, unreadable nested subqueries with modular, readable `WITH cte_name AS (...)` blocks that emulate step-by-step data transformations.
- **Analytic Window Functions:** The true milestone of Intermediate SQL. Unlike `GROUP BY`, which collapses rows into summary records, window functions compute aggregate and ranking metrics over a sliding window while preserving every individual row:
  - `ROW_NUMBER() OVER (PARTITION BY ... ORDER BY ...)` for isolated Top-N ranking per category.
  - `SUM(...) OVER (ORDER BY ... ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)` for cumulative Year-to-Date running calculations.

---

## 3. What I Solved: Projects & Practical Applications

### Project 1: Comparative Airport Weather Analysis (6 Global Hubs)

We analyzed 2014 daily weather feeds for six global airport hubs. To guarantee system resilience, I engineered an ingestion pipeline that queries the Azure SQL database and automatically caches local CSV backups. If network dropouts or firewall blocks occur, the pipeline seamlessly falls back to reading the local cache.

#### 📊 2014 Meteorological Summary Table:

| Hub / Airport | Annual Mean Temp (°C) | Record High (°C) | Record Low (°C) | Annual Temp Swing (°C) | Annual Rain (mm) | Wet Days (>0mm) | Max Wind (km/h) |
| :--- | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| **Brasília (BSB)** | **22.9** | 36 | 9 | 27 | **751.6** | 102 | 195 |
| **Cape Town (CPT)** | 17.6 | 37 | 1 | 36 | 428.2 | 74 | 58 |
| **Delhi (DEL)** | 13.7 | 38 | -17 | 55 | 225.3 | 78 | **209** |
| **Beijing (PEK)** | 13.4 | **42** | -13 | 55 | 405.9 | 56 | 72 |
| **London (LHR/LCY)** | 12.3 | 30 | -4 | 34 | 503.1 | **170** | 66 |
| **Moscow (SVO)** | **6.0** | 33 | **-26** | **59** | 0.0* | 0* | 47 |

*\*Note: Moscow 2014 precipitation sensors were unrecorded in the legacy telemetry feed.*

#### 🛫 Aviation & Meteorological Insights:
1. **Continentality vs. Equatorial Moderation:**
   Moscow exhibited extreme continental swings (**59°C** swing, dropping to **-26°C** in winter and reaching **33°C** in summer), demanding extensive winter de-icing infrastructure and specialized runway snow clearance. In contrast, Brasília enjoyed tropical stability (**22.9°C** mean, **27°C** swing), ensuring predictable aircraft takeoff weight calculations year-round.
2. **Precipitation Regimes & Flight Operations:**
   London experienced rain on **170 days** (~47% of the year), but with a modest annual volume of **503.1 mm** (classic low-intensity oceanic drizzle and persistent low cloud ceilings requiring constant Low Visibility Procedures). Conversely, Brasília accumulated **751.6 mm** across only **102 wet days** (>7.3 mm per wet day), driven by intense tropical convective thunderstorms that pose severe hydroplaning and standing-water risks on runways.
3. **Severe Wind Hazards:**
   Delhi and Brasília recorded extreme wind gusts of **209 km/h** and **195 km/h** respectively, linked to violent pre-monsoon squall lines and convective microbursts that represent acute hazards during final approach and landing.

---

### Project 2: The 10-Task Intermediate SQL Assessment (10 / 10 Score)

Every query was evaluated against cryptographic SHA-256 result fingerprints in the assessment notebook:

1. **Schema Introspection:** Queried `INFORMATION_SCHEMA.COLUMNS` to audit table column counts across the `week06` schema.
2. **Handling Messy Data & NULLs:** Identified 6 days in London where precipitation was logged (>0 mm) even though the categorical `[ Events]` string was `NULL`.
3. **Customer Churn Analysis:** Quantified customer retention risk, demonstrating that Month-to-Month contracts suffered a **57.6%** churn rate compared to **27.1%** for Two-Year contracts.
4. **Export Partner Consistency (`GROUP BY + HAVING`):** Filtered UK dairy export records to identify partners trading across all 12 distinct months of 2014, with Ireland leading at **$421.2M**.
5. **Epidemiological JOIN Across Schemas:** Joined WHO TB surveillance data with World Bank population censuses to compute per-capita mortality rates (Djibouti highest at 100.6 per 100k, Nigeria at 92.6 per 100k).
6. **Anti-Join Data Audit:** Pinpointed **28 unmatched sovereign states** between WHO and World Bank data due to naming discrepancies.
7. **Stacking Entities with `UNION ALL`:** Vertically stacked all six airport datasets to compute overall annual mean temperatures in a single unified pass.
8. **Window Ranking (`ROW_NUMBER()`):** Partitioned London weather by month to isolate the single hottest calendar day per month with deterministic date ordering.
9. **Cumulative Window Totals:** Computed a cumulative Year-to-Date (YTD) running sum of UK dairy exports, tracking the growth curve from $87.1M in January to $898.6M by December.
10. **Business Risk & Ethical Data Auditing:** Evaluated a loan approval dataset by property area and credit history.

---

## 4. Challenges Faced & How I Overcame Them

The real learning happened when queries failed or returned deceptive results:

### ⚠️ Challenge 1: The Silent Integer Division Trap in T-SQL
When computing customer churn percentages, my initial query returned `0` for all categories.
- **The Cause:** In Microsoft SQL Server, dividing an integer by an integer performs integer division and truncates the decimal remainder toward zero (`1 / 2 = 0`). Because `Churn` was stored as an integer (`0` or `1`), `AVG(Churn)` evaluated to `0`.
- **The Fix:** Promoted the operand to a float by pre-multiplying: `ROUND(100.0 * AVG(1.0 * Churn), 1)`.

### ⚠️ Challenge 2: The Phantom Spaces in Schema Column Names
Querying `[Events]` from `week06.london_2014` threw an `Invalid column name` error despite seeing the column in `.head()`.
- **The Cause:** Inspecting `INFORMATION_SCHEMA.COLUMNS` revealed that the column header literally had a leading whitespace: `' Events'`.
- **The Fix:** Wrapped the exact column name with its leading space inside brackets: `[ Events]`, and sanitized all DataFrames upon ingestion using `col.strip()`.

### ⚠️ Challenge 3: Entity Resolution & Anti-Join Mismatches
When joining WHO tuberculosis records with World Bank population data on `Country`, 28 countries dropped out of the analysis.
- **The Cause:** Discrepancies in country nomenclature (e.g., WHO's `"Bolivia (Plurinational State of)"` vs. World Bank's `"Bolivia"`, or `"United States of America"` vs. `"United States"`).
- **The Fix:** In production pipelines, string matching on country names must be replaced with standardized **ISO 3166-1 alpha-3 codes** (e.g., `BOL`, `USA`, `NGA`) or a managed synonym crosswalk table.

### ⚠️ Challenge 4: The Synthetic Bias Trap in Task 10
In Task 10, grouping loan applications by `Property_Area` and `Credit_History` yielded an astonishing result:
- **Rural:** 166 applications, 100% had `Credit_History = 0`, **0.0%** approved.
- **Semiurban:** 167 applications, 100% had `Credit_History = 1`, **100.0%** approved.
- **Urban:** 167 applications, 100% had `Credit_History = 1`, **100.0%** approved.
- **The Insight:** This dataset contains artificial data leakage. If an ML engineer trained a predictive credit scoring model on this raw data without auditing, the model would learn that geography is an absolute proxy for creditworthiness, resulting in severe algorithmic redlining and discrimination against rural borrowers.

---

## 5. Key Takeaways & Advice for Fellow Learners

1. **SQL at the Edge, Pandas at the Core:** Push data filtering, joining, and heavy aggregation to the database server where indexes and query optimizers live. Pull only the required analytical dataset into Python for visualization and feature engineering.
2. **Never Trust an `INNER JOIN` Blindly:** Always perform an anti-join (`LEFT JOIN ... WHERE right.id IS NULL`) first to understand what data you are dropping on the floor.
3. **Build Offline-First Resiliency:** When developing against cloud databases, implement automatic local caching. It protects you from firewall reconfigurations, network timeouts, and unnecessary cloud billing egress.
4. **Be a Critical Data Auditor:** Numbers can mislead. Always inspect data distributions and look out for synthetic artifacts, biased proxies, and missing records.

---

*Thank you to the mentors and cohort at DataraFlow for an exhilarating Week 6. Next stop: Machine Learning and advanced predictive modeling!*